"""creating app tables

Revision ID: 31eed0f89308
Revises: 
Create Date: 2021-09-08 19:21:12.866289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31eed0f89308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('secret', sa.String(length=87), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_name'), 'app', ['name'], unique=True)
    op.create_table('app_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_access')
    op.drop_index(op.f('ix_app_name'), table_name='app')
    op.drop_table('app')
    # ### end Alembic commands ###
